### ISSUE TITLE
Unable to update queue ranked types:

### ISSUE THREAD

**Issue by iamEvanYT** [steven4547466/MatchmakingService#10]
When I try to join a queue (same map name) with two different rating types, it shows this error until I use ```:Clear()```
Is this a error or did I set it up incorrectly?

![Screenshot 2021-12-19 at 9 57 21 AM](https://user-images.githubusercontent.com/47493765/146670895-5bf426ea-7236-4a42-9638-71683217a421.png)

**Comment by iamEvanYT** [comment]
I think I found a possible fix to this bug.
On line 147: ```elseif old[ratingType] ~= nil then```
should be changed to ```elseif old[ratingType] == nil then```

**Comment by steven4547466** [comment]
Merged #11, this should be fixed.
