### ISSUE TITLE
checkForParties: attempt to index number with number

### ISSUE THREAD

**Issue by iamEvanYT** [steven4547466/MatchmakingService#12]
New issue when trying to queue a party: @steven4547466 
![Screenshot 2021-12-21 at 6 21 52 PM](https://user-images.githubusercontent.com/47493765/146979734-450c5406-5586-4c7e-bb05-e93cc92192b8.png)

**Comment by steven4547466** [comment]
Hm, that's odd. There's nil checks before every checkForParty so it shouldn't be possible. How often do you see this issue?

**Comment by steven4547466** [comment]
Ah never mind. I think I found the issue.

**Comment by steven4547466** [comment]
Commit https://github.com/steven4547466/MatchmakingService/commit/36996b84815970f8694618b172f51d45c416a69c should fix this issue
