### ISSUE TITLE
MatchmakingService.PlayerRemovedFromQueue not firing when using :RemovePlayersFromQueue()

### ISSUE THREAD

**Issue by iamEvanYT** [steven4547466/MatchmakingService#14]
MatchmakingService.PlayerRemovedFromQueue not firing when using :RemovePlayersFromQueue()

**Comment by steven4547466** [comment]
The event will only fire if the player was actually in the queue:

https://user-images.githubusercontent.com/23726534/149231582-114a381c-2195-4de8-ad17-ff740000d090.mp4


Can you make sure they're actually in the queue first and if it's still happening can you show me some code?

**Comment by iamEvanYT** [comment]
i think i used queuepartyid at first

**Comment by steven4547466** [comment]
I'll look into it.

**Comment by steven4547466** [comment]
Sorry for the extended wait. College started again not too recently so I've been busy. I should be able to get to this by monday.

**Comment by iamEvanYT** [comment]
Hi!
I used this code:
```
-- Obtain the service
local MatchmakingService = require(7567983240).GetSingleton()
MatchmakingService:SetPlayerRange("Map 1", NumberRange.new(2, 2)) -- 2, 2 means min players 2, max players 2 (or 1v1)

-- Set the game place, this game must exist in the same universe
MatchmakingService:AddGamePlace("Map 1", 137781385)-- fake game place

-- Queue players (you can call QueuePlayer from anywhere)
function PlayerAdded(p)
	wait(1)
	print("queuing",p)
	MatchmakingService:QueueParty({p}, "queue", "Map 1") -- "queue" can be any string you want, so can the map
	wait(2)
	print("Removing")
	MatchmakingService:RemovePlayersFromQueue({p})
end

MatchmakingService.PlayerRemovedFromQueue:Connect(function(player, map, ratingType, roundedRating)
	print("PlayerRemovedFromQueue","player",player, "map",map,"ratingType", ratingType,"roundedRating", roundedRating)
end)

game.Players.PlayerAdded:Connect(function(p)
	PlayerAdded(p)
end)

for i, p in ipairs(game.Players:GetPlayers()) do
	PlayerAdded(p)
end
```
and the PlayerRemovedFromQueue Fired.

**Comment by iamEvanYT** [comment]
hi! i think i found the bug. when you save the parties, u use "_" to split the map,ratingType,skillLevel.
My map's name is "SwordWars_1v1" so it splited it wrongly: Map: SwordWars, ratingType: 1v1
Not sure why this doesn't happen to QueuePlayerId though

**Comment by iamEvanYT** [comment]
Should i change my queue name or are you gonna use another string to split it?

**Comment by steven4547466** [comment]
Ah, alright. I'm going to add an additional underscore when saving the queue so that this doesn't happen. I'm currently on my way to college, but I will make this change when I get home

**Comment by iamEvanYT** [comment]
Also, (this is another topic) if theres a running game with not enough player, the other players in queue will not be teleported into it, so the running game will yield for inf sec (not enough players to start) . Is this expected or a bug?

**Comment by steven4547466** [comment]
> Also, (this is another topic) if theres a running game with not enough player, the other players in queue will not be teleported into it, so the running game will yield for inf sec (not enough players to start) . Is this expected or a bug?

If the game has its joinable set to false, then yes, it is expected. If the game is still joinable then it's a bug. Also rating type is taken into account for running games as well. If the game has still joinable then open a new issue, otherwise it's expected. Games will auto clear themselves from memory eventually.

Either way, the main topic of this issue was fixed in https://github.com/steven4547466/MatchmakingService/commit/e8c3e7fc5544e9e1141896ca7f6c15d7bc97494a. Just don't make a map with two underscores right next to each other.

**Comment by iamEvanYT** [comment]
Thx!
