### ISSUE TITLE
Error when trying to use MatchmakingService source code module

### ISSUE THREAD

**Issue by itfoldy** [steven4547466/MatchmakingService#17]
I wanted to modify a part of MatchmakingService's source code, so I copied the source code into a new module and required it. 

![image](https://user-images.githubusercontent.com/76444336/163413812-aeecadff-68ca-46fd-9314-98369e2664dd.png)

I noticed that the source code doesn't include OpenSkill and Signal (which should be a parent of the module)
which are here in the module:
`16 local OpenSkill = require(script.OpenSkill)`
`17 local Signal = require(script.Signal)`

Also the reason I wanted to modify it is, because when queuing for a match, and when it prints "Added game" shortly after it throws out an error and doesn't teleport you. This issue occurs on `Line 537`, and the error is that `Argument 2 doesn't exist.`
Here is the contents of Line 537:
`teleportDataMemory:SetAsync(g.key, data, 600)`

My temporary fix to stop errors, was that I made it into this:
`if data then`
`  teleportDataMemory:SetAsync(g.key, data, 600)`
`else`
`  warn("Line 537 : No data")`
`end`

For some reason, data doesn't exist when trying to teleport the player, but once in a while it worked randomly without any fix. Very weird.

**Comment by itfoldy** [comment]
Trying to get an screenshot of the `Argument 2 doesn't exist.` error, but now it works perfectly again..
Please include OpenSkill and Signal into the source code though!

**Comment by itfoldy** [comment]
![image](https://user-images.githubusercontent.com/76444336/163479524-7c9e6131-7339-4704-a531-d0151b9bd149.png)
got the error to show up again, after some time trying to randomly join the game and queue in

**Comment by steven4547466** [comment]
I can't exactly include the source for those because this github doesn't house the model, it's just the source code for the main part. You can always get the latest module from here: https://www.roblox.com/library/7567983240/MatchmakingService which will include the dependencies.

If I add them here I would need to add 9 more files which isn't great. But like I said you should be able to get the module with the dependencies straight from roblox.

As for the `Argument 2 missing or nil`, how often does it happen?

**Comment by itfoldy** [comment]
Just woke up, went into the game, tried queueing & the error pops up. Whenever I try to play it a bunch of times (meaning open a new server a bunch of times), then it randomly after a few tries starts to work. Could be something with servers, or..? 
Basically the error happens every time, unless you open a new server a bunch of times..?

I also tried queuing again after getting the error in the same server, but my queue handler automatically detected that the player was now in a party, but the player's party was nil before queuing for the first time. Anyways, didn't teleport me anyway, probably because player data wasn't cleared..? (I was just thinking maybe the error is only for first time queuing)

**Comment by steven4547466** [comment]
Do you set any custom teleport data? I think this was just a dumb mistake on my part not checking if custom teleport data was set before attempting to add it...

**Comment by steven4547466** [comment]
I just released 2.0.3 which should hopefully fix this issue. If you see it again, please reopen this issue.
