### ISSUE TITLE
attempt to index nil with "(mapname)"

### ISSUE THREAD

**Issue by Issue3996** [steven4547466/MatchmakingService#23]
Issue at line 292/299 (set player range, add game place depending on which order you have them initialise)
not sure why this issue is happening, as I haven't touched the matchmaking code in a while. Would be appreciated if it could be looked into, as I rely on this codebase 

thanks :)

**Comment by steven4547466** [comment]
Please provide a full error if you still have it.

**Comment by Issue3996** [comment]
"ServerScriptService.MatchmakingService:361: attempt to index nil with 'levl1'"
```function MatchmakingService:SetPlayerRange(map: string, newPlayerRange: NumberRange)
	if newPlayerRange.Max > 100 then
		warn("Maximum players has a cap of 100.")
	end
	self.PlayerRanges[map] = newPlayerRange <<<- issue is here
end
```

**Comment by Issue3996** [comment]
resolved issue, other code was causing error
