### ISSUE TITLE
MatchmakingService wont find a match (error)

### ISSUE THREAD

**Issue by katalindev** [steven4547466/MatchmakingService#4]
![image](https://user-images.githubusercontent.com/65962979/137598511-e7c895ad-6c16-4692-8e96-c2009e920b03.png)
It also slows down downloading data from roblox's servers using profile service. Took 1min to load my data from the last play test

**Comment by katalindev** [comment]
Small note : I was playing on 2 devices, one which was already in a game

**Comment by katalindev** [comment]
![image](https://user-images.githubusercontent.com/65962979/137599157-a15688a5-07fc-450f-a5c8-6e1b25db25e3.png)

**Comment by katalindev** [comment]
doing MatchmakingService:Clear() after requiring the module seems to have fixed the issue

**Comment by katalindev** [comment]
Update : it only worked once, since then the data from ProfileService wont get loaded, no errors, just queues of requests

**Comment by katalindev** [comment]
![image](https://user-images.githubusercontent.com/65962979/137600349-722a953c-0703-4672-9f1e-0c3acc37ed4d.png)
errors upon calling MatchmakingService:StartGame()

**Comment by steven4547466** [comment]
These errors don't have to do with profile service, these have to do with memoryservice. I'm working on making the data saved smaller so it allows for more room in memory, though it really should not be hitting the limit. As for the nil index and transformation function, I'll look into those as well. Thank you for the reports

**Comment by steven4547466** [comment]
Just an update on this, `StartGame()` issue was resolved and "The provided value is too long" issue is still being looked into. I have a way that would reduce memory by a few bytes per player so I don't know if it'll actually make a difference, but it is being looked into. Sorry for the extended wait

**Comment by steven4547466** [comment]
Just an update on here since I forgot to (I did on devforum), I submitted the issue as a bug and I hope they look into it.

**Comment by steven4547466** [comment]
Roblox Bug Support moved my report to the engine bugs topic, so I hope they look into it asap! You can view it here: https://devforum.roblox.com/t/bug-in-memorystoreservice-sortedmap-memory-size-quota/1526388

**Comment by steven4547466** [comment]
They still havent responded 😕

**Comment by steven4547466** [comment]
A fix has been implemented and is being monitored
