### ISSUE TITLE
attempt to index nil with 'joinable'

### ISSUE THREAD

**Issue by markplays111** [steven4547466/MatchmakingService#5]
![image_2021-11-25_113245](https://user-images.githubusercontent.com/70047155/143375172-b1d07a9b-0273-40d3-af2d-d393d0967cf3.png)

**Comment by steven4547466** [comment]
I've released an update that may inadvertently fix this issue due to changes on how matchmaking works, can you confirm that it still happens in `3.4.0-beta`?

**Comment by markplays111** [comment]
It no longer happens in 3.4.0-beta however I am left with a new problem. "attempt to index nil with number'. 
![image](https://user-images.githubusercontent.com/70047155/143508655-de4e8d62-9bd4-458f-bffa-fc1f8b08d208.png)

**Comment by steven4547466** [comment]
Sorry about that, I just pushed 3.4.1-beta and it should now be fixed.

**Comment by markplays111** [comment]
Great job on this!
