### ISSUE TITLE
Code: 4, Error: The Provided value is too long.

### ISSUE THREAD

**Issue by iamEvanYT** [steven4547466/MatchmakingService#6]
@steven4547466 
Version: 4.1.0
Happened After ```MatchmakingService:QueuePlayerId(player.UserId, "ranked", GameType)```

[](url
![Screenshot 2021-12-18 at 4 20 43 PM](https://user-images.githubusercontent.com/47493765/146648157-b9f420bc-07fd-42b1-a446-fe16e32c1ae9.png)
)

Script:
```lua
local MatchmakingService = require(8267761365).GetSingleton()

local InQueue = {}

function PlayerAdded(player)
	MatchmakingService:ClearPlayerInfoId(player.UserId)
	MatchmakingService:RemovePlayerFromQueueId(player.UserId)
	InQueue[player] = nil
end

for _,plr in pairs(game:GetService("Players"):GetPlayers()) do PlayerAdded(plr) end
game:GetService("Players").PlayerAdded:Connect(PlayerAdded)

MatchmakingService:SetMatchmakingInterval(2)

local GameTypes = {
	["CrystalWars_1v1_unranked"] = {
		GamePlace = 8279938771;
		PlayerRange = NumberRange.new(2, 2)
	};
}

for Name,Details in pairs(GameTypes) do
	local GamePlace = Details.GamePlace
	local PlayerRange = Details.PlayerRange
	MatchmakingService:SetPlayerRange(Name, PlayerRange)
	MatchmakingService:AddGamePlace(Name, GamePlace)
end

-- Queue players (you can call QueuePlayer from anywhere)
game:GetService("ServerStorage").QueuePlayer.Event:Connect(function(player,GameType,Ranked)
	if InQueue[player] == nil then
		MatchmakingService:RemovePlayerFromQueue(player)
		local Success = false
		pcall(function()
			if Ranked == true then
				Success = MatchmakingService:QueuePlayerId(player.UserId, "ranked", GameType)
			else
				Success = MatchmakingService:QueuePlayerId(player.UserId, "unranked", GameType)
			end
		end)
		if Success == true then
			InQueue[player] = true
			game:GetService("ReplicatedStorage").JoinedQueue:FireClient(player,GameType)
		end
	end
end)

game:GetService("ReplicatedStorage").LeaveQueue.OnServerEvent:Connect(function(player)
	MatchmakingService:RemovePlayerFromQueueId(player.UserId)
	MatchmakingService:ClearPlayerInfoId(player.UserId)
	InQueue[player] = nil
end)

game:GetService("Players").PlayerRemoving:Connect(function(player)
	MatchmakingService:RemovePlayerFromQueueId(player.UserId)
	InQueue[player] = nil
end)

game:BindToClose(function()
	MatchmakingService:RemovePlayersFromQueue(game:GetService("Players"):GetPlayers())
end)
```

**Comment by steven4547466** [comment]
Interesting, this issue was meant to be fixed. I'll look into it

**Comment by steven4547466** [comment]
Could you run `require(MatchmakingServiceLocation).GetSingleton():Clear()` in your console while in game then restart the game servers and see if that works? If it doesn't I'll have to give you a special version of matchmakingservice for debugging purposes.

**Comment by iamEvanYT** [comment]
done.
i tried it a lot of times
after a few times joining it started again.

**Comment by steven4547466** [comment]
Huh. That's odd. I'll definitely keep an eye on it. Reopen this issue if it happens again and I'll get you the additional debug information

**Comment by iamEvanYT** [comment]
It just happened again...
I was testing with two accounts after another ```require(8267761365).GetSingleton():Clear()```
![Screenshot 2021-12-18 at 5 13 55 PM](https://user-images.githubusercontent.com/47493765/146649937-e8f0ae13-09c1-4bf7-9574-73f9cfd4e1c3.png)

**Comment by steven4547466** [comment]
Can you try with the rbxm in this zip? It contains additional information that will help us figure out what's going on.
[MatchmakingService (2).zip](https://github.com/steven4547466/MatchmakingService/files/7739681/MatchmakingService.2.zip)

**Comment by iamEvanYT** [comment]
![Screenshot 2021-12-18 at 5 49 41 PM](https://user-images.githubusercontent.com/47493765/146650982-7d708e63-f4d2-46d6-a8ae-36582215fb25.png)
Here!
But we can still teleport after that.

**Comment by steven4547466** [comment]
Hm. It seems like the tables have the same values and are not being split properly. I've added something that may fix that. Before you run this can you run a clear though? So go in game, clear, then use this module and restart servers. Additionally you can just put a clear in your script that requires it so it clears on join just for testing purposes

[MatchmakingService (3).zip](https://github.com/steven4547466/MatchmakingService/files/7739694/MatchmakingService.3.zip)

**Comment by evanchan0819** [comment]
![Screenshot 2021-12-18 at 6 09 41 PM](https://user-images.githubusercontent.com/47493765/146651526-236dc99b-1413-4a9c-ad00-f7a509b448a0.png)
Nothing in output. I waited a long time.

**Comment by iamEvanYT** [comment]
There is something now:
![Screenshot 2021-12-18 at 6 11 54 PM](https://user-images.githubusercontent.com/47493765/146651563-a0979b7a-1141-49bf-95d4-c02e56374bd8.png)
![Screenshot 2021-12-18 at 6 11 57 PM](https://user-images.githubusercontent.com/47493765/146651568-d733fafe-4bfc-4feb-bfc4-9cf949dd21a6.png)

**Comment by steven4547466** [comment]
I'm going to see if I can replicate your issue on my private servers for now, I'll get back to you shortly

**Comment by steven4547466** [comment]
Alright I think I finally got to the bottom of this. I think it had to do with players not being properly removed from the queue which was causing everything to mess up. Also, make sure in your game servers that you're using `RemoveGame` in BindToClose, as that could be the reason why your running games is getting overpopulated. Anyways, try the module below and hopefully it all works

[MatchmakingService (4).zip](https://github.com/steven4547466/MatchmakingService/files/7739758/MatchmakingService.4.zip)

**Comment by iamEvanYT** [comment]
Its teleporting fine after i cleared it.
But these are still here:

<img width="1280" alt="Screenshot 2021-12-18 at 6 47 16 PM" src="https://user-images.githubusercontent.com/47493765/146652592-4649957f-4e32-4afa-ac1e-1974a02bc454.png">
<img width="1280" alt="Screenshot 2021-12-18 at 6 47 24 PM" src="https://user-images.githubusercontent.com/47493765/146652594-e0e739f4-e84e-499f-9327-677f9c13537a.png">
<img width="1280" alt="Screenshot 2021-12-18 at 6 47 26 PM" src="https://user-images.githubusercontent.com/47493765/146652597-a543c89a-e488-4634-8628-8d00bab434fe.png">

**Comment by iamEvanYT** [comment]
Here are the place files: @steven4547466 
[Matchmaking.zip](https://github.com/steven4547466/MatchmakingService/files/7739780/Matchmaking.zip)

**Comment by steven4547466** [comment]
Hm, I removed those prints. It seems like you only updated the version in your match.rbxl file and not the lobby.rbxl file.

Actually, it seems like I uploaded the wrong file. One moment.

[MatchmakingService (5).zip](https://github.com/steven4547466/MatchmakingService/files/7739793/MatchmakingService.5.zip)

This should be the right file. If this issue is _still happening_ after this, then I'll just run a longer extensive test, but that would take a while which is why I'm avoiding it.

**Comment by evanchan0819** [comment]
oh ok. thank you for letting me know!
let me try later when i get home.

**Comment by iamEvanYT** [comment]
![Screenshot 2021-12-18 at 7 43 56 PM](https://user-images.githubusercontent.com/47493765/146653830-47c3c0b1-c4ad-4bd9-8881-cbf0b08f45b3.png)
This is the fifth one

**Comment by iamEvanYT** [comment]
After I reseted it and I rejoined a match with my friend, the same error appeared.
Then I used ```print(game:GetService("MemoryStoreService"):GetSortedMap("MATCHMAKINGSERVICE"):GetAsync("RunningGamesCount"))```
It returned 2.
The teleporting worked.
After I left the game server, i used ```print(game:GetService("MemoryStoreService"):GetSortedMap("MATCHMAKINGSERVICE"):GetAsync("RunningGamesCount"))``` again.
It also returned 2
I already put :BindToClose() on the top of the script.

**Comment by steven4547466** [comment]
Alright, I have my test running. I'm gonna leave it up for about 10 minutes and see what data I can gather about the issue

**Comment by iamEvanYT** [comment]
I just tested for a little bit and I think ```print(game:GetService("MemoryStoreService"):GetSortedMap("MATCHMAKINGSERVICE"):GetAsync("RunningGamesCount"))``` returns 2 and won't deduct when I called ```:RemoveGame()``` because The ReservedServer Id Cannot Save.
In your module (5) line 1510: ```table.find(runningGames, gameId)```
it can't find any because it didn't set it. @steven4547466

**Comment by steven4547466** [comment]
Yeah, the problem is it isn't being set because the value is too big, it's meant to be split. I think I've got it, but I'm gonna let it run for a little longer.

**Comment by steven4547466** [comment]
[MatchmakingService (6).zip](https://github.com/steven4547466/MatchmakingService/files/7739917/MatchmakingService.6.zip)

Alright, I ran this for about 10 minutes and went into 30 games simultaneously. It should work now.

**Comment by iamEvanYT** [comment]
Ok. I just cleared the store to test.
Uh oh... Its
![Screenshot 2021-12-18 at 8 32 50 PM](https://user-images.githubusercontent.com/47493765/146654828-32096403-78ec-4559-b872-30516a1ca3dd.png)

**Comment by iamEvanYT** [comment]
> Ok. I just cleared the store to test. Uh oh... Its ![Screenshot 2021-12-18 at 8 32 50 PM](https://user-images.githubusercontent.com/47493765/146654828-32096403-78ec-4559-b872-30516a1ca3dd.png)

Let me clear it again.

**Comment by iamEvanYT** [comment]
Well, i don't think it works.
![Screenshot 2021-12-18 at 8 39 00 PM](https://user-images.githubusercontent.com/47493765/146654938-2c8d6171-9e37-4b98-b553-6cf383fe2f50.png)
Does it work with your testing place?

**Comment by steven4547466** [comment]
It does work in my testing place. I was able to run 30 games without error. I'm going to reupload this to make sure it's right. I don't know why it's giving you so much trouble...

[MatchmakingService (7).zip](https://github.com/steven4547466/MatchmakingService/files/7739928/MatchmakingService.7.zip)

**Comment by iamEvanYT** [comment]
Well... It turns out that the last one you sent **MatchmakingService (6).zip** is the old one.

**Comment by steven4547466** [comment]
So is **MatchmakingService (7).zip** working?

**Comment by iamEvanYT** [comment]
Im still testing and i don't think so
I might have forgot to publish.. idk

**Comment by iamEvanYT** [comment]
![Screenshot 2021-12-18 at 8 49 36 PM](https://user-images.githubusercontent.com/47493765/146655141-a5af692e-f755-4402-be70-d5b381766662.png)
I don't think its working
I published a few times already.

**Comment by steven4547466** [comment]
Was this after a clear?

**Comment by iamEvanYT** [comment]
yes

**Comment by iamEvanYT** [comment]
do you want the game files?

**Comment by steven4547466** [comment]
Sure

**Comment by iamEvanYT** [comment]
[Matchmaking.zip](https://github.com/steven4547466/MatchmakingService/files/7739941/Matchmaking.zip)

**Comment by steven4547466** [comment]
It actually worked for me
![ap5o7_11650 1](https://user-images.githubusercontent.com/23726534/146655379-9aa2e712-fcc6-479c-8356-2452a275e59e.jpeg)
![kxqu7_11651 1](https://user-images.githubusercontent.com/23726534/146655381-0316c862-7615-4b68-9fd3-1b3e2329474d.png)

I didn't edit anything. This was just out of the box

**Comment by iamEvanYT** [comment]
wait. i think i found the issue

**Comment by iamEvanYT** [comment]
on line 500: ```memory:SetAsync("RunningGamesCount", 1, 86400)```
shouldn't the Running GameCount be 0?

**Comment by iamEvanYT** [comment]
ohh i see what your trying to do

**Comment by steven4547466** [comment]
It could be, but it doesn't need to be. It's just an increment. I start it at 0 if there is no running games. I'm just confused on why it works for me but not for you

**Comment by steven4547466** [comment]
By chance does your place have team create enabled? I could look at it directly if you want.

**Comment by iamEvanYT** [comment]
it worked now 
Thank you for helping me solve this issue!

**Comment by steven4547466** [comment]
Ah, alright. If any other issues come up, let me know

**Comment by iamEvanYT** [comment]
i just used script to clear it at first

**Comment by iamEvanYT** [comment]
oh and should I change it back to using the asset id? @steven4547466

**Comment by steven4547466** [comment]
I've uploaded the new version to roblox, so yeah you can.

**Comment by iamEvanYT** [comment]
thank you!

**Comment by iamEvanYT** [comment]
Hi. I think when you have only 1 game running, when you :RemoveGame() , The RunningGamesCount will become 0.
@steven4547466

**Comment by iamEvanYT** [comment]
Idk if you have fixed it when you updated it on the roblox model
