### ISSUE TITLE
Unable to update running games: Failed to invoke transformation function

### ISSUE THREAD

**Issue by iamEvanYT** [steven4547466/MatchmakingService#7]
Happened after player left.

Bug: ```MatchmakingService:RemovePlayerFromGameId(player.UserId, _G.gameId)	```

Script:
```lua
local GameEnded = false

function EndGame(winner)
	GameEnded = true
	game:GetService("ReplicatedStorage").Win:FireAllClients(winner.Name)
	wait(2)
	--MatchmakingService:UpdateRatings(_G.ratingType, {if winner == 1 then 1 else 2, if winner == 2 then 1 else 2}, {t1, t2})
	for i, v in ipairs(game.Players:GetPlayers()) do
		game:GetService("TeleportService"):Teleport(8275005629,v)
	end
	repeat wait() until #game:GetService("Players"):GetPlayers() == 0
	MatchmakingService:RemoveGame(_G.gameId)
end

game.Players.PlayerRemoving:Connect(function(player)
	if GameEnded == false then
		**MatchmakingService:RemovePlayerFromGameId(player.UserId, _G.gameId)**		
		if game:GetService("Players"):GetPlayers() == 1 then
			EndGame(game:GetService("Players"):GetPlayers()[1])
		end
	end
end)
```
![Screenshot 2021-12-18 at 4 26 52 PM](https://user-images.githubusercontent.com/47493765/146648423-be9bcbff-aae6-4f99-a822-feb14327d0bc.png)

**Comment by steven4547466** [comment]
This is actually a documentation problem. I forgot to mention that player ranges on game servers should match those of hub servers. I believe this even extends into my example games.

I've updated the example servers and added this into the documentation.

Basically to fix this, add `MatchmakingService:SetPlayerRange(MapNameHere, NumberRangeHere)` to your game server. Make sure your map name and number range match that of the hub servers. If this doesn't work, reopen this issue
